using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Progress.Sitefinity.AspNetCore.ViewComponents;
using Progress.Sitefinity.AspNetCore.ViewComponents.AttributeConfigurator.Attributes;
using Progress.Sitefinity.Renderer.Designers;
using Progress.Sitefinity.Renderer.Designers.Attributes;
using Progress.Sitefinity.Renderer.Entities.Content;

namespace ViewComponents.Mohan
{
    /// <summary>
    /// Test widget with different kind of restrictions for its properties. For more information on creating widgets
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/asp.net-core-widget-components">this page.</see>
    /// </summary>
    [SitefinityWidget]
    public class MohanViewComponent : ViewComponent
    {
        /// <summary>
        /// Invokes the view.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public IViewComponentResult Invoke(IViewComponentContext<MohanEntity> context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            return this.View(context.Entity);
        }
    }

    /// <summary>
    /// The test model for the load tests widget. For a list of supported properties
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/autogenerated-field-types">this page.</see>
    /// </summary>
    public class MohanEntity
    {
        /// <summary>
        /// Gets or sets a value indicating whether a boolean property is true or false.
        /// </summary>
        public string Message { get; set; }
        public int MyNumber {get; set;}
        public DateTime MyDateTime {get; set;}

        [ReadOnly(true)]
        public string Readonly { get; set; }

        [Browsable(false)]
        public string NotBrowsable { get; set; }

        [EmailAddress(ErrorMessage = "Enter valid email.")]
        [DisplayName("Email field")]
        public string EmailField { get; set; }

        [Placeholder("This is the placeholder")]
        public string PlaceHolderProp { get; set; }

        [DataType(customDataType: KnownFieldTypes.Password)]
        public string Password { get; set; }

        [ColorPalette("Default")]
        public string ColorField { get; set; }

        [Content(Type = KnownContentTypes.Images, AllowMultipleItemsSelection = false)]
        public MixedContentContext Images { get; set; }

        [Content(Type = KnownContentTypes.News)]
        public MixedContentContext News { get; set; }

        [Content(Type = KnownContentTypes.Pages, AllowMultipleItemsSelection = false, DisableInteraction = true, ShowSiteSelector = true)]
        public MixedContentContext Page { get; set; }
    }
}
